apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y8p53gyma-go 
  janus-idp.io/tekton: y8p53gyma-go
  backstage.io/kubernetes-id: y8p53gyma-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y8p53gyma-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml